SET DEFINE OFF
SET SERVEROUTPUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

-- 기존 운영 DB에 최근 애플리케이션 변경을 반영한다.
-- 각 DDL은 USER_* 메타데이터를 확인하므로 적용 도중 중단돼도 같은 파일을 다시 실행할 수 있다.

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'MEMBER'
       AND COLUMN_NAME = 'VERSION';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE MEMBER ADD (VERSION NUMBER(19,0) DEFAULT 0 NOT NULL)';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'ADMIN_USER'
       AND COLUMN_NAME = 'LOCKED_AT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ADMIN_USER ADD (LOCKED_AT TIMESTAMP(6))';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'INQUIRY'
       AND COLUMN_NAME = 'ANSWER_READ_AT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE INQUIRY ADD (ANSWER_READ_AT TIMESTAMP(6))';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'PAYMENT_ORDER'
       AND COLUMN_NAME = 'SUBSCRIPTION_STARTED_AT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PAYMENT_ORDER ADD (SUBSCRIPTION_STARTED_AT TIMESTAMP(6))';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'PAYMENT_ORDER'
       AND COLUMN_NAME = 'SUBSCRIPTION_ENDED_AT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PAYMENT_ORDER ADD (SUBSCRIPTION_ENDED_AT TIMESTAMP(6))';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'PAYMENT_ORDER'
       AND COLUMN_NAME = 'VERSION';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE PAYMENT_ORDER ADD (VERSION NUMBER(19,0) DEFAULT 0 NOT NULL)';
    END IF;
END;
/

-- 구독 부여기간 컬럼 도입 전에 승인된 주문도 환불 시 회수할 수 있게 전환한다.
-- 기존 승인 시각을 시작으로 사용하고 결제 주기에 맞춰 종료 시각을 계산한다.
UPDATE PAYMENT_ORDER
   SET SUBSCRIPTION_STARTED_AT = COALESCE(APPROVED_AT, CREATED_AT),
       SUBSCRIPTION_ENDED_AT = ADD_MONTHS(
           COALESCE(APPROVED_AT, CREATED_AT),
           CASE BILLING_CYCLE WHEN 'YEARLY' THEN 12 ELSE 1 END)
 WHERE STATUS = 'PAID'
   AND (SUBSCRIPTION_STARTED_AT IS NULL OR SUBSCRIPTION_ENDED_AT IS NULL);

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
      FROM PAYMENT_ORDER
     WHERE STATUS = 'PAID'
       AND (SUBSCRIPTION_STARTED_AT IS NULL OR SUBSCRIPTION_ENDED_AT IS NULL);
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20002,
            '기존 PAID 주문의 구독 부여기간 전환에 실패했습니다. 결제 데이터를 확인하세요.');
    END IF;
END;
/

COMMIT;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
      FROM USER_CONSTRAINTS
     WHERE CONSTRAINT_NAME = 'CK_PAY_SUB_PERIOD';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'~
            ALTER TABLE PAYMENT_ORDER ADD CONSTRAINT CK_PAY_SUB_PERIOD CHECK (
                (SUBSCRIPTION_STARTED_AT IS NULL AND SUBSCRIPTION_ENDED_AT IS NULL)
                OR (SUBSCRIPTION_STARTED_AT IS NOT NULL
                    AND SUBSCRIPTION_ENDED_AT IS NOT NULL
                    AND SUBSCRIPTION_STARTED_AT < SUBSCRIPTION_ENDED_AT)
            )
        ~';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'SHEDLOCK';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'~
            CREATE TABLE SHEDLOCK (
                NAME       VARCHAR2(64)  NOT NULL,
                LOCK_UNTIL TIMESTAMP(3)  NOT NULL,
                LOCKED_AT  TIMESTAMP(3)  NOT NULL,
                LOCKED_BY  VARCHAR2(255) NOT NULL,
                CONSTRAINT PK_SHEDLOCK PRIMARY KEY (NAME)
            )
        ~';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'LOGIN_RATE_HIT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'~
            CREATE TABLE LOGIN_RATE_HIT (
                RATE_KEY VARCHAR2(120) NOT NULL,
                HIT_AT   TIMESTAMP     NOT NULL
            )
        ~';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'RATE_LIMIT_BUCKET';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'~
            CREATE TABLE RATE_LIMIT_BUCKET (
                RATE_KEY            VARCHAR2(120) NOT NULL,
                WINDOW_STARTED_AT   TIMESTAMP     NOT NULL,
                HIT_COUNT           NUMBER(9)     DEFAULT 0 NOT NULL,
                UPDATED_AT          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_RATE_LIMIT_BUCKET PRIMARY KEY (RATE_KEY)
            )
        ~';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'AI_REPORT_QUOTA';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'~
            CREATE TABLE AI_REPORT_QUOTA (
                QUOTA_KEY  VARCHAR2(80) NOT NULL,
                CNT        NUMBER(9)    DEFAULT 0 NOT NULL,
                UPDATED_AT TIMESTAMP    DEFAULT SYSTIMESTAMP NOT NULL,
                CONSTRAINT PK_AI_REPORT_QUOTA PRIMARY KEY (QUOTA_KEY)
            )
        ~';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'SPRING_SESSION';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'~
            CREATE TABLE SPRING_SESSION (
                PRIMARY_ID            CHAR(36 CHAR)     NOT NULL,
                SESSION_ID            CHAR(36 CHAR)     NOT NULL,
                CREATION_TIME         NUMBER(19,0)      NOT NULL,
                LAST_ACCESS_TIME      NUMBER(19,0)      NOT NULL,
                MAX_INACTIVE_INTERVAL NUMBER(10,0)      NOT NULL,
                EXPIRY_TIME           NUMBER(19,0)      NOT NULL,
                PRINCIPAL_NAME        VARCHAR2(100 CHAR),
                CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
            )
        ~';
    END IF;

    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'SPRING_SESSION_ATTRIBUTES';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'~
            CREATE TABLE SPRING_SESSION_ATTRIBUTES (
                SESSION_PRIMARY_ID CHAR(36 CHAR)      NOT NULL,
                ATTRIBUTE_NAME     VARCHAR2(200 CHAR) NOT NULL,
                ATTRIBUTE_BYTES    BLOB               NOT NULL,
                CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK
                    PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
                CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK
                    FOREIGN KEY (SESSION_PRIMARY_ID)
                    REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE
            )
        ~';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
    v_duplicates NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'UX_BATCH_JOB_RUNNING';
    IF v_count = 0 THEN
        SELECT COUNT(*) INTO v_duplicates
          FROM (
              SELECT DATASET_CD
                FROM BATCH_JOB_LOG
               WHERE STATUS = 'RUNNING'
               GROUP BY DATASET_CD
              HAVING COUNT(*) > 1
          );
        IF v_duplicates > 0 THEN
            RAISE_APPLICATION_ERROR(-20001,
                'UX_BATCH_JOB_RUNNING 생성 전 중복 RUNNING 배치를 정리해야 합니다.');
        END IF;
        EXECUTE IMMEDIATE q'~
            CREATE UNIQUE INDEX UX_BATCH_JOB_RUNNING
                ON BATCH_JOB_LOG (CASE WHEN STATUS = 'RUNNING' THEN DATASET_CD END)
        ~';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'IX_LOGIN_RATE_HIT';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX IX_LOGIN_RATE_HIT ON LOGIN_RATE_HIT (RATE_KEY, HIT_AT)';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'IX_RATE_LIMIT_BUCKET_UPDATED';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX IX_RATE_LIMIT_BUCKET_UPDATED ON RATE_LIMIT_BUCKET (UPDATED_AT)';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'SPRING_SESSION_IX1';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID)';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'SPRING_SESSION_IX2';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME)';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM USER_INDEXES
     WHERE INDEX_NAME = 'SPRING_SESSION_IX3';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME)';
    END IF;
END;
/

PROMPT 운영 스키마 변경 적용 완료
