-- 소상공인 상권분석 DB 스키마
-- Oracle 19c 기준
-- 생성 순서: 기준 데이터 -> 분석 데이터 -> 회원/관리자

-- 기준 데이터
-- 분기 기준
CREATE TABLE DIM_QUARTER (
                             STDR_YYQU_CD   CHAR(5 CHAR)      NOT NULL,
  BASE_YEAR      NUMBER(4,0)       NOT NULL,
  QUARTER_NO     NUMBER(1,0)       NOT NULL,
  QUARTER_LABEL  VARCHAR2(20 CHAR) NOT NULL,
  QU_STRT_DT     DATE,
  QU_END_DT      DATE,
  CREATED_AT     TIMESTAMP(6)      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT     TIMESTAMP(6)      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_DIM_QUARTER PRIMARY KEY (STDR_YYQU_CD),
  CONSTRAINT CK_DQ_FORMAT   CHECK (REGEXP_LIKE(STDR_YYQU_CD, '^[0-9]{4}[1-4]$')),
  CONSTRAINT CK_DQ_YEAR     CHECK (BASE_YEAR BETWEEN 2000 AND 2100),
  CONSTRAINT CK_DQ_QNO      CHECK (QUARTER_NO BETWEEN 1 AND 4),
  CONSTRAINT CK_DQ_DERIVED  CHECK (
        BASE_YEAR  = TO_NUMBER(SUBSTR(STDR_YYQU_CD,1,4))
    AND QUARTER_NO = TO_NUMBER(SUBSTR(STDR_YYQU_CD,5,1))),
  CONSTRAINT CK_DQ_DATES    CHECK (QU_STRT_DT IS NULL OR QU_END_DT IS NULL
                                   OR QU_END_DT >= QU_STRT_DT)
);
COMMENT ON TABLE  DIM_QUARTER               IS '분기 차원 테이블. STDR_YYQU_CD = 연도4자리+분기1자리 (예: 20241)';
COMMENT ON COLUMN DIM_QUARTER.STDR_YYQU_CD  IS '기준 년분기 코드 (예: 20241 = 2024년 1분기)';
COMMENT ON COLUMN DIM_QUARTER.BASE_YEAR     IS '연도 (기준코드 앞 4자리)';
COMMENT ON COLUMN DIM_QUARTER.QUARTER_NO    IS '분기 1~4 (기준코드 끝 1자리)';

-- 상권 기본 정보
CREATE TABLE TRDAR (
                       TRDAR_CD        VARCHAR2(20 CHAR)  NOT NULL,
                       TRDAR_CD_NM     VARCHAR2(200 CHAR) NOT NULL,
                       TRDAR_SE_CD     CHAR(1 CHAR)       NOT NULL,
  TRDAR_SE_CD_NM  VARCHAR2(50 CHAR)  NOT NULL,
  SIGNGU_CD       VARCHAR2(20 CHAR),
  SIGNGU_NM       VARCHAR2(50 CHAR),
  ADSTRD_CD       VARCHAR2(20 CHAR),
  ADSTRD_NM       VARCHAR2(50 CHAR),
  CENTER_LOT      NUMBER(11,8),
  CENTER_LAT      NUMBER(10,8),
  GEO_JSON        CLOB,
  CREATED_AT      TIMESTAMP(6)       DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT      TIMESTAMP(6)       DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_TRDAR     PRIMARY KEY (TRDAR_CD),
  CONSTRAINT CK_TRDAR_SE  CHECK (TRDAR_SE_CD IN ('A','D','R','U')),
  CONSTRAINT CK_TRDAR_LOT CHECK (CENTER_LOT IS NULL OR CENTER_LOT BETWEEN -180 AND 180),
  CONSTRAINT CK_TRDAR_LAT CHECK (CENTER_LAT IS NULL OR CENTER_LAT BETWEEN  -90 AND  90),
  CONSTRAINT CK_TRDAR_GEO CHECK (GEO_JSON IS JSON)
);
COMMENT ON TABLE  TRDAR                IS '상권 마스터. GEO_JSON은 상권 경계 폴리곤 좌표(GeoJSON)';
COMMENT ON COLUMN TRDAR.TRDAR_CD       IS '상권 코드 (PK)';
COMMENT ON COLUMN TRDAR.TRDAR_SE_CD    IS '상권 구분: A 골목상권 / D 발달상권 / R 전통시장 / U 관광특구';
COMMENT ON COLUMN TRDAR.SIGNGU_CD      IS '자치구 코드 (COMMERCIAL_RENT/FRANCHISE_COUNT 지역 조인용).';
COMMENT ON COLUMN TRDAR.ADSTRD_CD      IS '행정동 코드 (지역 조인용).';
COMMENT ON COLUMN TRDAR.CENTER_LOT     IS '대표 경도 (지도 핀 배치용; GeoJSON 파싱 불요).';
COMMENT ON COLUMN TRDAR.CENTER_LAT     IS '대표 위도 (지도 핀 배치용).';
COMMENT ON COLUMN TRDAR.GEO_JSON       IS '상권 폴리곤 좌표 (GeoJSON).';
CREATE INDEX IX_TRDAR_SE     ON TRDAR (TRDAR_SE_CD, TRDAR_CD);
CREATE INDEX IX_TRDAR_SIGNGU ON TRDAR (SIGNGU_CD);

-- 업종 기본 정보
CREATE TABLE INDUTY (
                        INDUTY_CD        VARCHAR2(20 CHAR)  NOT NULL,
                        INDUTY_CD_NM     VARCHAR2(200 CHAR) NOT NULL,
                        INDUTY_LCLAS_CD  VARCHAR2(20 CHAR),
                        INDUTY_LCLAS_NM  VARCHAR2(200 CHAR),
                        INDUTY_MLSFC_CD  VARCHAR2(20 CHAR),
                        INDUTY_MLSFC_NM  VARCHAR2(200 CHAR),
                        CREATED_AT       TIMESTAMP(6)       DEFAULT SYSTIMESTAMP NOT NULL,
                        UPDATED_AT       TIMESTAMP(6)       DEFAULT SYSTIMESTAMP NOT NULL,
                        CONSTRAINT PK_INDUTY PRIMARY KEY (INDUTY_CD)
);
COMMENT ON TABLE  INDUTY             IS '업종 마스터 (대/중/소분류 포함)';
COMMENT ON COLUMN INDUTY.INDUTY_CD   IS '서비스 업종 코드 (소분류, PK).';

-- 매출/점포 데이터
-- 분기별 상권/업종 매출
CREATE TABLE SALES (
                       STDR_YYQU_CD        CHAR(5 CHAR)      NOT NULL,
  TRDAR_CD            VARCHAR2(20 CHAR) NOT NULL,
  INDUTY_CD           VARCHAR2(20 CHAR) NOT NULL,
  THSMON_SELNG_AMT    NUMBER(18,0)      NOT NULL,
  THSMON_SELNG_CO     NUMBER(12,0)      NOT NULL,
  MON_SELNG_AMT       NUMBER(18,0)      DEFAULT 0 NOT NULL,
  TUES_SELNG_AMT      NUMBER(18,0)      DEFAULT 0 NOT NULL,
  WED_SELNG_AMT       NUMBER(18,0)      DEFAULT 0 NOT NULL,
  THUR_SELNG_AMT      NUMBER(18,0)      DEFAULT 0 NOT NULL,
  FRI_SELNG_AMT       NUMBER(18,0)      DEFAULT 0 NOT NULL,
  SAT_SELNG_AMT       NUMBER(18,0)      DEFAULT 0 NOT NULL,
  SUN_SELNG_AMT       NUMBER(18,0)      DEFAULT 0 NOT NULL,
  TMZON_00_06_SELNG_AMT NUMBER(18,0)    DEFAULT 0 NOT NULL,
  TMZON_06_11_SELNG_AMT NUMBER(18,0)    DEFAULT 0 NOT NULL,
  TMZON_11_14_SELNG_AMT NUMBER(18,0)    DEFAULT 0 NOT NULL,
  TMZON_14_17_SELNG_AMT NUMBER(18,0)    DEFAULT 0 NOT NULL,
  TMZON_17_21_SELNG_AMT NUMBER(18,0)    DEFAULT 0 NOT NULL,
  TMZON_21_24_SELNG_AMT NUMBER(18,0)    DEFAULT 0 NOT NULL,
  ML_SELNG_AMT        NUMBER(18,0)      DEFAULT 0 NOT NULL,
  FML_SELNG_AMT       NUMBER(18,0)      DEFAULT 0 NOT NULL,
  AGRDE_10_SELNG_AMT  NUMBER(18,0)      DEFAULT 0 NOT NULL,
  AGRDE_20_SELNG_AMT  NUMBER(18,0)      DEFAULT 0 NOT NULL,
  AGRDE_30_SELNG_AMT  NUMBER(18,0)      DEFAULT 0 NOT NULL,
  AGRDE_40_SELNG_AMT  NUMBER(18,0)      DEFAULT 0 NOT NULL,
  AGRDE_50_SELNG_AMT  NUMBER(18,0)      DEFAULT 0 NOT NULL,
  AGRDE_60_ABOVE_SELNG_AMT NUMBER(18,0) DEFAULT 0 NOT NULL,
  CREATED_AT          TIMESTAMP(6)      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT          TIMESTAMP(6)      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_SALES PRIMARY KEY (STDR_YYQU_CD, TRDAR_CD, INDUTY_CD),
  CONSTRAINT FK_SALES_QU   FOREIGN KEY (STDR_YYQU_CD) REFERENCES DIM_QUARTER (STDR_YYQU_CD),
  CONSTRAINT FK_SALES_TRD  FOREIGN KEY (TRDAR_CD)     REFERENCES TRDAR (TRDAR_CD),
  CONSTRAINT FK_SALES_IND  FOREIGN KEY (INDUTY_CD)    REFERENCES INDUTY (INDUTY_CD),
  CONSTRAINT CK_SALES_AMT_NN  CHECK (THSMON_SELNG_AMT >= 0),
  CONSTRAINT CK_SALES_CO_NN   CHECK (THSMON_SELNG_CO  >= 0),
  CONSTRAINT CK_SALES_WD_NN   CHECK (MON_SELNG_AMT>=0 AND TUES_SELNG_AMT>=0 AND WED_SELNG_AMT>=0
                                 AND THUR_SELNG_AMT>=0 AND FRI_SELNG_AMT>=0 AND SAT_SELNG_AMT>=0 AND SUN_SELNG_AMT>=0),
  CONSTRAINT CK_SALES_TZ_NN   CHECK (TMZON_00_06_SELNG_AMT>=0 AND TMZON_06_11_SELNG_AMT>=0 AND TMZON_11_14_SELNG_AMT>=0
                                 AND TMZON_14_17_SELNG_AMT>=0 AND TMZON_17_21_SELNG_AMT>=0 AND TMZON_21_24_SELNG_AMT>=0),
  CONSTRAINT CK_SALES_GEN_NN  CHECK (ML_SELNG_AMT>=0 AND FML_SELNG_AMT>=0),
  CONSTRAINT CK_SALES_AGE_NN  CHECK (AGRDE_10_SELNG_AMT>=0 AND AGRDE_20_SELNG_AMT>=0 AND AGRDE_30_SELNG_AMT>=0
                                 AND AGRDE_40_SELNG_AMT>=0 AND AGRDE_50_SELNG_AMT>=0 AND AGRDE_60_ABOVE_SELNG_AMT>=0)
);
COMMENT ON TABLE  SALES                  IS '추정매출. 단위: 분기 x 상권 x 업종';
COMMENT ON COLUMN SALES.STDR_YYQU_CD     IS '기준 년분기 코드 (PK, 분기 FK)';
COMMENT ON COLUMN SALES.THSMON_SELNG_AMT IS '당월 매출 금액(원)';
COMMENT ON COLUMN SALES.THSMON_SELNG_CO  IS '당월 매출 건수.';
CREATE INDEX IX_SALES_TRD_AMT ON SALES (STDR_YYQU_CD, TRDAR_CD,  THSMON_SELNG_AMT);
CREATE INDEX IX_SALES_IND_AMT ON SALES (STDR_YYQU_CD, INDUTY_CD, THSMON_SELNG_AMT);

-- 분기별 점포 통계
CREATE TABLE STORE_STAT (
                            STDR_YYQU_CD      CHAR(5 CHAR)      NOT NULL,
  TRDAR_CD          VARCHAR2(20 CHAR) NOT NULL,
  INDUTY_CD         VARCHAR2(20 CHAR) NOT NULL,
  STOR_CO           NUMBER(10,0)      DEFAULT 0 NOT NULL,
  SIMILR_INDUTY_STOR_CO NUMBER(10,0)  DEFAULT 0 NOT NULL,
  OPBIZ_RT          NUMBER(7,3),
  CLSBIZ_RT         NUMBER(7,3),
  OPBIZ_STOR_CO     NUMBER(10,0)      DEFAULT 0 NOT NULL,
  CLSBIZ_STOR_CO    NUMBER(10,0)      DEFAULT 0 NOT NULL,
  FRC_STOR_CO       NUMBER(10,0)      DEFAULT 0 NOT NULL,
  CREATED_AT        TIMESTAMP(6)      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP(6)      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_STORE_STAT PRIMARY KEY (STDR_YYQU_CD, TRDAR_CD, INDUTY_CD),
  CONSTRAINT FK_STORE_QU  FOREIGN KEY (STDR_YYQU_CD) REFERENCES DIM_QUARTER (STDR_YYQU_CD),
  CONSTRAINT FK_STORE_TRD FOREIGN KEY (TRDAR_CD)     REFERENCES TRDAR (TRDAR_CD),
  CONSTRAINT FK_STORE_IND FOREIGN KEY (INDUTY_CD)    REFERENCES INDUTY (INDUTY_CD),
  CONSTRAINT CK_STORE_CO_NN   CHECK (STOR_CO>=0 AND SIMILR_INDUTY_STOR_CO>=0 AND OPBIZ_STOR_CO>=0
                                 AND CLSBIZ_STOR_CO>=0 AND FRC_STOR_CO>=0),
  CONSTRAINT CK_STORE_RT_RNG  CHECK ((OPBIZ_RT  IS NULL OR OPBIZ_RT  BETWEEN 0 AND 100)
                                 AND (CLSBIZ_RT IS NULL OR CLSBIZ_RT BETWEEN 0 AND 100))
);
COMMENT ON TABLE  STORE_STAT           IS '점포 통계. 단위: 분기 x 상권 x 업종 (가장 큰 테이블)';
COMMENT ON COLUMN STORE_STAT.STOR_CO   IS '점포 수.';
COMMENT ON COLUMN STORE_STAT.FRC_STOR_CO IS '프랜차이즈 점포 수.';
COMMENT ON COLUMN STORE_STAT.OPBIZ_RT  IS '개업률(%) 0..100. NULL 허용(원천 미제공 분기); 점포수와 독립.';
CREATE INDEX IX_STORE_TRD ON STORE_STAT (STDR_YYQU_CD, TRDAR_CD) ;
CREATE INDEX IX_STORE_IND ON STORE_STAT (STDR_YYQU_CD, INDUTY_CD, TRDAR_CD);

-- 상권 특성 데이터
-- 집객시설 정보
CREATE TABLE ATTRACTION (
                            STDR_YYQU_CD    CHAR(5 CHAR)      NOT NULL,
  TRDAR_CD        VARCHAR2(20 CHAR) NOT NULL,
  VIATR_FCLTY_CO  NUMBER(10,0) DEFAULT 0 NOT NULL,
  SUBWAY_STATN_CO NUMBER(10,0) DEFAULT 0 NOT NULL,
  BUS_STOP_CO     NUMBER(10,0) DEFAULT 0 NOT NULL,
  SCHOOL_CO       NUMBER(10,0) DEFAULT 0 NOT NULL,
  HOSPITAL_CO     NUMBER(10,0) DEFAULT 0 NOT NULL,
  BANK_CO         NUMBER(10,0) DEFAULT 0 NOT NULL,
  CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_ATTRACTION PRIMARY KEY (STDR_YYQU_CD, TRDAR_CD),
  CONSTRAINT FK_ATTR_QU  FOREIGN KEY (STDR_YYQU_CD) REFERENCES DIM_QUARTER (STDR_YYQU_CD),
  CONSTRAINT FK_ATTR_TRD FOREIGN KEY (TRDAR_CD)     REFERENCES TRDAR (TRDAR_CD),
  CONSTRAINT CK_ATTR_NN  CHECK (VIATR_FCLTY_CO>=0 AND SUBWAY_STATN_CO>=0 AND BUS_STOP_CO>=0
                            AND SCHOOL_CO>=0 AND HOSPITAL_CO>=0 AND BANK_CO>=0)
);
COMMENT ON TABLE  ATTRACTION                IS '집객시설. 단위: 분기 x 상권';
COMMENT ON COLUMN ATTRACTION.VIATR_FCLTY_CO IS '집객시설 수 (총)';
CREATE INDEX IX_ATTR_TRD ON ATTRACTION (TRDAR_CD);

-- 상권 변화 지표
CREATE TABLE TRDAR_CHANGE (
                              STDR_YYQU_CD      CHAR(5 CHAR)      NOT NULL,
  TRDAR_CD          VARCHAR2(20 CHAR) NOT NULL,
  TRDAR_CHNGE_IX    CHAR(2 CHAR)      NOT NULL,
  TRDAR_CHNGE_IX_NM VARCHAR2(50 CHAR),
  OPR_SALE_MT_AVRG  NUMBER(8,2),
  CLS_SALE_MT_AVRG  NUMBER(8,2),
  CREATED_AT     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_TRDAR_CHANGE PRIMARY KEY (STDR_YYQU_CD, TRDAR_CD),
  CONSTRAINT FK_TCHG_QU  FOREIGN KEY (STDR_YYQU_CD) REFERENCES DIM_QUARTER (STDR_YYQU_CD),
  CONSTRAINT FK_TCHG_TRD FOREIGN KEY (TRDAR_CD)     REFERENCES TRDAR (TRDAR_CD),
  CONSTRAINT CK_TCHG_IX  CHECK (TRDAR_CHNGE_IX IN ('HH','HL','LH','LL')),
  CONSTRAINT CK_TCHG_MT  CHECK ((OPR_SALE_MT_AVRG IS NULL OR OPR_SALE_MT_AVRG>=0)
                            AND (CLS_SALE_MT_AVRG IS NULL OR CLS_SALE_MT_AVRG>=0))
);
COMMENT ON TABLE  TRDAR_CHANGE                   IS '상권 변화지표. 단위: 분기 x 상권';
COMMENT ON COLUMN TRDAR_CHANGE.TRDAR_CHNGE_IX    IS '변화지표 코드 HH/HL/LH/LL.';
COMMENT ON COLUMN TRDAR_CHANGE.TRDAR_CHNGE_IX_NM IS '변화지표명 (상세 페이지 라벨; 재조회 불요).';
CREATE INDEX IX_TCHG_TRD ON TRDAR_CHANGE (TRDAR_CD);

-- 유동인구
CREATE TABLE STREET_POP (
                            STDR_YYQU_CD  CHAR(5 CHAR)      NOT NULL,
  TRDAR_CD      VARCHAR2(20 CHAR) NOT NULL,
  TOT_FLPOP_CO  NUMBER(14,0) DEFAULT 0 NOT NULL,
  ML_FLPOP_CO   NUMBER(14,0) DEFAULT 0 NOT NULL,
  FML_FLPOP_CO  NUMBER(14,0) DEFAULT 0 NOT NULL,
  AGRDE_10_FLPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  AGRDE_20_FLPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  AGRDE_30_FLPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  AGRDE_40_FLPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  AGRDE_50_FLPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  AGRDE_60_ABOVE_FLPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  TMZON_00_06_FLPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  TMZON_06_11_FLPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  TMZON_11_14_FLPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  TMZON_14_17_FLPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  TMZON_17_21_FLPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  TMZON_21_24_FLPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  MON_FLPOP_CO  NUMBER(14,0) DEFAULT 0 NOT NULL,
  TUES_FLPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  WED_FLPOP_CO  NUMBER(14,0) DEFAULT 0 NOT NULL,
  THUR_FLPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  FRI_FLPOP_CO  NUMBER(14,0) DEFAULT 0 NOT NULL,
  SAT_FLPOP_CO  NUMBER(14,0) DEFAULT 0 NOT NULL,
  SUN_FLPOP_CO  NUMBER(14,0) DEFAULT 0 NOT NULL,
  CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_STREET_POP PRIMARY KEY (STDR_YYQU_CD, TRDAR_CD),
  CONSTRAINT FK_SPOP_QU  FOREIGN KEY (STDR_YYQU_CD) REFERENCES DIM_QUARTER (STDR_YYQU_CD),
  CONSTRAINT FK_SPOP_TRD FOREIGN KEY (TRDAR_CD)     REFERENCES TRDAR (TRDAR_CD),
  CONSTRAINT CK_SPOP_NN  CHECK (TOT_FLPOP_CO>=0 AND ML_FLPOP_CO>=0 AND FML_FLPOP_CO>=0
     AND AGRDE_10_FLPOP_CO>=0 AND AGRDE_20_FLPOP_CO>=0 AND AGRDE_30_FLPOP_CO>=0
     AND AGRDE_40_FLPOP_CO>=0 AND AGRDE_50_FLPOP_CO>=0 AND AGRDE_60_ABOVE_FLPOP_CO>=0
     AND TMZON_00_06_FLPOP_CO>=0 AND TMZON_06_11_FLPOP_CO>=0 AND TMZON_11_14_FLPOP_CO>=0
     AND TMZON_14_17_FLPOP_CO>=0 AND TMZON_17_21_FLPOP_CO>=0 AND TMZON_21_24_FLPOP_CO>=0
     AND MON_FLPOP_CO>=0 AND TUES_FLPOP_CO>=0 AND WED_FLPOP_CO>=0 AND THUR_FLPOP_CO>=0
     AND FRI_FLPOP_CO>=0 AND SAT_FLPOP_CO>=0 AND SUN_FLPOP_CO>=0)
);
COMMENT ON TABLE STREET_POP IS '길단위 유동인구. 단위: 분기 x 상권';
CREATE INDEX IX_SPOP_TRD ON STREET_POP (TRDAR_CD);

-- 상주인구
CREATE TABLE RESIDENT_POP (
                              STDR_YYQU_CD  CHAR(5 CHAR)      NOT NULL,
  TRDAR_CD      VARCHAR2(20 CHAR) NOT NULL,
  TOT_REPOP_CO  NUMBER(14,0) DEFAULT 0 NOT NULL,
  ML_REPOP_CO   NUMBER(14,0) DEFAULT 0 NOT NULL,
  FML_REPOP_CO  NUMBER(14,0) DEFAULT 0 NOT NULL,
  AGRDE_10_REPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  AGRDE_20_REPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  AGRDE_30_REPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  AGRDE_40_REPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  AGRDE_50_REPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  AGRDE_60_ABOVE_REPOP_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  TOT_HSHLD_CO         NUMBER(14,0) DEFAULT 0 NOT NULL,
  APT_HSHLD_RESIDENT_CO     NUMBER(14,0) DEFAULT 0 NOT NULL,
  NON_APT_HSHLD_RESIDENT_CO NUMBER(14,0) DEFAULT 0 NOT NULL,
  CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_RESIDENT_POP PRIMARY KEY (STDR_YYQU_CD, TRDAR_CD),
  CONSTRAINT FK_RPOP_QU  FOREIGN KEY (STDR_YYQU_CD) REFERENCES DIM_QUARTER (STDR_YYQU_CD),
  CONSTRAINT FK_RPOP_TRD FOREIGN KEY (TRDAR_CD)     REFERENCES TRDAR (TRDAR_CD),
  CONSTRAINT CK_RPOP_NN  CHECK (TOT_REPOP_CO>=0 AND ML_REPOP_CO>=0 AND FML_REPOP_CO>=0
     AND AGRDE_10_REPOP_CO>=0 AND AGRDE_20_REPOP_CO>=0 AND AGRDE_30_REPOP_CO>=0
     AND AGRDE_40_REPOP_CO>=0 AND AGRDE_50_REPOP_CO>=0 AND AGRDE_60_ABOVE_REPOP_CO>=0
     AND TOT_HSHLD_CO>=0 AND APT_HSHLD_RESIDENT_CO>=0 AND NON_APT_HSHLD_RESIDENT_CO>=0)
);
COMMENT ON TABLE  RESIDENT_POP IS '상주인구. 단위: 분기 x 상권';
COMMENT ON COLUMN RESIDENT_POP.APT_HSHLD_RESIDENT_CO     IS '상주인구 기준 아파트 가구수 (APT.APT_HSHLD_CO 와 의미 다름).';
COMMENT ON COLUMN RESIDENT_POP.NON_APT_HSHLD_RESIDENT_CO IS '상주인구 기준 비아파트 가구수.';
CREATE INDEX IX_RPOP_TRD ON RESIDENT_POP (TRDAR_CD);

-- 아파트 정보
CREATE TABLE APT (
                     STDR_YYQU_CD  CHAR(5 CHAR)      NOT NULL,
  TRDAR_CD      VARCHAR2(20 CHAR) NOT NULL,
  APT_COMPLX_CO NUMBER(10,0) DEFAULT 0 NOT NULL,
  APT_HSHLD_CO  NUMBER(12,0) DEFAULT 0 NOT NULL,
  AREA_66_HSHLD_CO   NUMBER(12,0) DEFAULT 0 NOT NULL,
  AREA_99_HSHLD_CO   NUMBER(12,0) DEFAULT 0 NOT NULL,
  AREA_132_HSHLD_CO  NUMBER(12,0) DEFAULT 0 NOT NULL,
  AREA_165_HSHLD_CO  NUMBER(12,0) DEFAULT 0 NOT NULL,
  PRC_1_HSHLD_CO  NUMBER(12,0) DEFAULT 0 NOT NULL,
  PRC_2_HSHLD_CO  NUMBER(12,0) DEFAULT 0 NOT NULL,
  PRC_3_HSHLD_CO  NUMBER(12,0) DEFAULT 0 NOT NULL,
  PRC_4_HSHLD_CO  NUMBER(12,0) DEFAULT 0 NOT NULL,
  PRC_5_HSHLD_CO  NUMBER(12,0) DEFAULT 0 NOT NULL,
  PRC_6_HSHLD_CO  NUMBER(12,0) DEFAULT 0 NOT NULL,
  AVRG_AREA       NUMBER(10,2),
  AVRG_MRKT_PRC   NUMBER(18,0),
  CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_APT PRIMARY KEY (STDR_YYQU_CD, TRDAR_CD),
  CONSTRAINT FK_APT_QU  FOREIGN KEY (STDR_YYQU_CD) REFERENCES DIM_QUARTER (STDR_YYQU_CD),
  CONSTRAINT FK_APT_TRD FOREIGN KEY (TRDAR_CD)     REFERENCES TRDAR (TRDAR_CD),
  CONSTRAINT CK_APT_NN  CHECK (APT_COMPLX_CO>=0 AND APT_HSHLD_CO>=0 AND AREA_66_HSHLD_CO>=0 AND AREA_99_HSHLD_CO>=0
     AND AREA_132_HSHLD_CO>=0 AND AREA_165_HSHLD_CO>=0
     AND PRC_1_HSHLD_CO>=0 AND PRC_2_HSHLD_CO>=0 AND PRC_3_HSHLD_CO>=0
     AND PRC_4_HSHLD_CO>=0 AND PRC_5_HSHLD_CO>=0 AND PRC_6_HSHLD_CO>=0
     AND (AVRG_AREA IS NULL OR AVRG_AREA>=0) AND (AVRG_MRKT_PRC IS NULL OR AVRG_MRKT_PRC>=0))
);
COMMENT ON TABLE  APT             IS '아파트 정보. 단위: 분기 x 상권';
COMMENT ON COLUMN APT.APT_HSHLD_CO IS '단지 기준 아파트 총 가구수 (RESIDENT_POP.APT_HSHLD_RESIDENT_CO 와 의미 다름).';
CREATE INDEX IX_APT_TRD ON APT (TRDAR_CD);

-- 외부/참조 데이터
-- 상업용 임대료/공실률
CREATE TABLE COMMERCIAL_RENT (
                                 RENT_ID       NUMBER(12,0) GENERATED ALWAYS AS IDENTITY,
                                 REGION_CD     VARCHAR2(20 CHAR)  NOT NULL,
                                 REGION_NM     VARCHAR2(200 CHAR) NOT NULL,
                                 RLST_TY_CD    VARCHAR2(20 CHAR)  DEFAULT 'ALL' NOT NULL,
                                 METRIC_CD     VARCHAR2(30 CHAR)  NOT NULL,
                                 METRIC_NM     VARCHAR2(100 CHAR),
                                 STDR_YYQU_CD  CHAR(5 CHAR)       NOT NULL,
  METRIC_VALUE  NUMBER(18,4)       NOT NULL,
  UOM           VARCHAR2(20 CHAR),
  CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_COMMERCIAL_RENT PRIMARY KEY (RENT_ID),
  CONSTRAINT UK_COMMERCIAL_RENT UNIQUE (REGION_CD, RLST_TY_CD, METRIC_CD, STDR_YYQU_CD),
  CONSTRAINT FK_RENT_QU     FOREIGN KEY (STDR_YYQU_CD) REFERENCES DIM_QUARTER (STDR_YYQU_CD),
  CONSTRAINT CK_RENT_METRIC CHECK (METRIC_CD IN ('RENT','VACANCY','YIELD','PRICE_INDEX'))
);
COMMENT ON TABLE  COMMERCIAL_RENT            IS '상업용 임대료/공실률/수익률/가격지수 (한국부동산원). 단위: 지역 x 부동산유형 x 지표 x 분기';
COMMENT ON COLUMN COMMERCIAL_RENT.RLST_TY_CD IS '부동산 유형 (원천에 구분 없으면 ALL로 저장, NOT NULL 유지)';
COMMENT ON COLUMN COMMERCIAL_RENT.METRIC_CD  IS '지표: RENT 임대료 / VACANCY 공실률 / YIELD 수익률 / PRICE_INDEX 가격지수';
CREATE INDEX IX_RENT_REGION ON COMMERCIAL_RENT (REGION_CD, STDR_YYQU_CD);
CREATE INDEX IX_RENT_FK_QU  ON COMMERCIAL_RENT (STDR_YYQU_CD);

-- 프랜차이즈 브랜드
CREATE TABLE FRANCHISE_BRAND (
                                 BRAND_MGMT_NO  VARCHAR2(30 CHAR)  NOT NULL,
                                 BRAND_NM       VARCHAR2(300 CHAR) NOT NULL,
                                 CORP_NM        VARCHAR2(300 CHAR),
                                 HQ_MGMT_NO     VARCHAR2(30 CHAR),
                                 BIZ_REG_NO     VARCHAR2(20 CHAR),
                                 INDUTY_LCLAS_NM VARCHAR2(200 CHAR),
                                 INDUTY_MLSFC_NM VARCHAR2(200 CHAR),
                                 BIZ_START_DE   DATE,
                                 CREATED_AT     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                 UPDATED_AT     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                 CONSTRAINT PK_FRANCHISE_BRAND PRIMARY KEY (BRAND_MGMT_NO)
);
COMMENT ON TABLE FRANCHISE_BRAND IS '프랜차이즈 브랜드 목록 (공정위)';
CREATE INDEX IX_FBRAND_NM     ON FRANCHISE_BRAND (BRAND_NM);
CREATE INDEX IX_FBRAND_UPNM   ON FRANCHISE_BRAND (UPPER(BRAND_NM));
CREATE INDEX IX_FBRAND_BIZREG ON FRANCHISE_BRAND (BIZ_REG_NO);

-- 지역별 가맹점 수
CREATE TABLE FRANCHISE_COUNT (
                                 FRC_CNT_ID    NUMBER(12,0) GENERATED ALWAYS AS IDENTITY,
                                 BASE_YEAR     NUMBER(4,0)        NOT NULL,
                                 AREA_CD       VARCHAR2(20 CHAR)  NOT NULL,
                                 AREA_NM       VARCHAR2(200 CHAR) NOT NULL,
                                 INDUTY_NM     VARCHAR2(200 CHAR) NOT NULL,
                                 FRC_CO        NUMBER(10,0)       NOT NULL,
                                 FRC_RT        NUMBER(9,4),
                                 CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                 UPDATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                 CONSTRAINT PK_FRANCHISE_COUNT PRIMARY KEY (FRC_CNT_ID),
                                 CONSTRAINT UK_FRANCHISE_COUNT UNIQUE (BASE_YEAR, AREA_CD, INDUTY_NM),
                                 CONSTRAINT CK_FCNT_YEAR CHECK (BASE_YEAR BETWEEN 2000 AND 2100),
                                 CONSTRAINT CK_FCNT_CO   CHECK (FRC_CO >= 0),
                                 CONSTRAINT CK_FCNT_RT   CHECK (FRC_RT IS NULL OR FRC_RT >= 0)
);
COMMENT ON TABLE  FRANCHISE_COUNT         IS '지역별 업종별 가맹점수 (공정위). 단위: 연도 x 지역 x 업종';
COMMENT ON COLUMN FRANCHISE_COUNT.AREA_CD IS '지역 코드 (NOT NULL; 명칭 변경에도 grain 안정). AREA_NM 은 표시용.';
CREATE INDEX IX_FRCNT_AREA ON FRANCHISE_COUNT (AREA_CD, BASE_YEAR);

-- 정보공개서 링크
CREATE TABLE FRANCHISE_DISCLOSURE (
                                      DISCLOSURE_SN VARCHAR2(30 CHAR)  NOT NULL,
                                      CORP_NM       VARCHAR2(300 CHAR),
                                      BRAND_NM      VARCHAR2(300 CHAR),
                                      BIZ_REG_NO    VARCHAR2(20 CHAR),
                                      VIEWER_URL    VARCHAR2(1000 CHAR),
                                      CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                      UPDATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                      CONSTRAINT PK_FRANCHISE_DISCLOSURE PRIMARY KEY (DISCLOSURE_SN)
);
COMMENT ON TABLE FRANCHISE_DISCLOSURE IS '정보공개서 목록 (공정위). 본문은 저장 안 함(실시간 API 조회)';
CREATE INDEX IX_FDISC_BRAND ON FRANCHISE_DISCLOSURE (BRAND_NM);

-- 업종별 주요 프랜차이즈 (브랜드 단위 가맹점수/평균매출)
CREATE TABLE FRANCHISE_BRAND_STAT (
                                      STAT_ID          NUMBER(12,0) GENERATED ALWAYS AS IDENTITY,
                                      INDUTY_CD        VARCHAR2(20 CHAR)  NOT NULL,
                                      BASE_YEAR        NUMBER(4,0)        NOT NULL,
                                      BRAND_NM         VARCHAR2(300 CHAR) NOT NULL,
                                      CORP_NM          VARCHAR2(300 CHAR),
                                      FTC_INDUTY_NM    VARCHAR2(200 CHAR),
                                      FRCS_CNT         NUMBER(10,0)       NOT NULL,
                                      AVG_SALES_AMT    NUMBER(15,0),
                                      NEW_FRCS_RGS_CNT NUMBER(10,0),
                                      CTRT_END_CNT     NUMBER(10,0),
                                      CTRT_CNCLTN_CNT  NUMBER(10,0),
                                      NM_CHG_CNT       NUMBER(10,0),
                                      CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                      UPDATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                      CONSTRAINT PK_FRANCHISE_BRAND_STAT PRIMARY KEY (STAT_ID),
                                      CONSTRAINT UK_FBSTAT UNIQUE (INDUTY_CD, BASE_YEAR, BRAND_NM),
                                      CONSTRAINT CK_FBSTAT_YEAR CHECK (BASE_YEAR BETWEEN 2000 AND 2100),
                                      CONSTRAINT CK_FBSTAT_CNT  CHECK (FRCS_CNT >= 0)
);
COMMENT ON TABLE  FRANCHISE_BRAND_STAT               IS '업종별 주요 프랜차이즈 (공정위 브랜드별 가맹점 현황). 서울 업종코드당 가맹점수 상위 5개만 저장';
COMMENT ON COLUMN FRANCHISE_BRAND_STAT.INDUTY_CD     IS '서울 상권 업종코드 (적재 시 공정위 중분류를 매핑)';
COMMENT ON COLUMN FRANCHISE_BRAND_STAT.FTC_INDUTY_NM IS '공정위 원본 업종 중분류명 (매핑 검증용)';
COMMENT ON COLUMN FRANCHISE_BRAND_STAT.AVG_SALES_AMT IS '가맹점 평균매출액 (천원, 정보공개서 기준)';

-- 업종별 상표 출원 동향 (KIPRIS)
CREATE TABLE INDUSTRY_TRADEMARK (
                                    TM_ID        NUMBER(12,0) GENERATED ALWAYS AS IDENTITY,
                                    INDUTY_CD    VARCHAR2(20 CHAR)  NOT NULL,
                                    APPL_NO      VARCHAR2(30 CHAR)  NOT NULL,
                                    TITLE        VARCHAR2(300 CHAR) NOT NULL,
                                    APPLICANT_NM VARCHAR2(300 CHAR),
                                    APPL_DATE    DATE,
                                    STATUS       VARCHAR2(30 CHAR),
                                    CREATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                    UPDATED_AT   TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                    CONSTRAINT PK_INDUSTRY_TRADEMARK PRIMARY KEY (TM_ID),
                                    CONSTRAINT UK_INDTM UNIQUE (INDUTY_CD, APPL_NO)
);
COMMENT ON TABLE  INDUSTRY_TRADEMARK           IS '업종별 상표 출원 동향 (KIPRIS 지정상품 검색). 업종당 최신 출원 5건만 저장';
COMMENT ON COLUMN INDUSTRY_TRADEMARK.INDUTY_CD IS '서울 상권 업종코드 (INDUTY 마스터의 업종명을 검색어로 정제)';
COMMENT ON COLUMN INDUSTRY_TRADEMARK.STATUS    IS 'KIPRIS 출원 상태 (출원/등록/거절 등 원문 그대로)';

-- 창업지원 사업: SUPPORT_PROGRAM (공통 마스터)
CREATE TABLE SUPPORT_PROGRAM (
                                 PROGRAM_ID       VARCHAR2(50 CHAR)   NOT NULL,
                                 SOURCE_CD        VARCHAR2(20 CHAR)   NOT NULL,
                                 TITLE            VARCHAR2(1000 CHAR) NOT NULL,
                                 PROGRAM_TYPE     VARCHAR2(100 CHAR),
                                 TARGET           VARCHAR2(1000 CHAR),
                                 REGION           VARCHAR2(100 CHAR),
                                 DESCRIPTION      CLOB,
                                 APPLY_BGNG_DE    DATE,
                                 APPLY_END_DE     DATE,
                                 APPLY_PERIOD_RAW VARCHAR2(200 CHAR),
                                 RECRUIT_YN       CHAR(1),
                                 IS_VISIBLE       CHAR(1) DEFAULT 'Y' NOT NULL,
                                 CONTACT          VARCHAR2(500 CHAR),
                                 DETAIL_URL       VARCHAR2(1000 CHAR),
                                 SOURCE_REG_DT    TIMESTAMP,
                                 CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                 UPDATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                 CONSTRAINT PK_SUPPORT_PROGRAM PRIMARY KEY (SOURCE_CD, PROGRAM_ID),
                                 CONSTRAINT CK_SPRG_SOURCE CHECK (SOURCE_CD IN ('BIZINFO','KSTARTUP')),
                                 CONSTRAINT CK_SPRG_RECRUIT CHECK (RECRUIT_YN IN ('Y','N') OR RECRUIT_YN IS NULL),
                                 CONSTRAINT CK_SPRG_VISIBLE CHECK (IS_VISIBLE IN ('Y','N')),
                                 CONSTRAINT CK_SPRG_PERIOD CHECK (APPLY_BGNG_DE IS NULL OR APPLY_END_DE IS NULL
                                     OR APPLY_END_DE >= APPLY_BGNG_DE)
);

COMMENT ON TABLE  SUPPORT_PROGRAM                  IS '창업지원 사업 (기업마당 + K-Startup 통합, SOURCE_CD로 구분)';
COMMENT ON COLUMN SUPPORT_PROGRAM.PROGRAM_ID        IS '지원 사업 ID (원본 소스 고유번호)';
COMMENT ON COLUMN SUPPORT_PROGRAM.SOURCE_CD         IS 'BIZINFO(기업마당) 또는 KSTARTUP(창업진흥원)';
COMMENT ON COLUMN SUPPORT_PROGRAM.TITLE             IS '제목';
COMMENT ON COLUMN SUPPORT_PROGRAM.PROGRAM_TYPE      IS '지원 사업 유형';
COMMENT ON COLUMN SUPPORT_PROGRAM.TARGET            IS '지원 대상 (예비창업자/소상공인 등 원문 텍스트)';
COMMENT ON COLUMN SUPPORT_PROGRAM.REGION            IS '지역명 (원문 그대로, 서울/전국 여부 판별용)';
COMMENT ON COLUMN SUPPORT_PROGRAM.DESCRIPTION       IS '지원 내용 (사업 소개 본문)';
COMMENT ON COLUMN SUPPORT_PROGRAM.APPLY_BGNG_DE     IS '신청 시작 일자';
COMMENT ON COLUMN SUPPORT_PROGRAM.APPLY_END_DE      IS '신청 종료 일자';
COMMENT ON COLUMN SUPPORT_PROGRAM.APPLY_PERIOD_RAW  IS '신청 기간 원문 (상시접수 등 날짜 아닌 값 보관)';
COMMENT ON COLUMN SUPPORT_PROGRAM.RECRUIT_YN        IS '모집 진행 여부 (원본 API 제공값, K-Startup만 채워짐)';
COMMENT ON COLUMN SUPPORT_PROGRAM.IS_VISIBLE        IS '관리자 노출 여부 (Y=노출,N=숨김). 배치는 절대 갱신하지 않음';
COMMENT ON COLUMN SUPPORT_PROGRAM.CONTACT           IS '문의처';
COMMENT ON COLUMN SUPPORT_PROGRAM.DETAIL_URL        IS '상세 URL';
COMMENT ON COLUMN SUPPORT_PROGRAM.SOURCE_REG_DT     IS '원본 사이트 등록일시';
COMMENT ON COLUMN SUPPORT_PROGRAM.CREATED_AT        IS '생성일시';
COMMENT ON COLUMN SUPPORT_PROGRAM.UPDATED_AT        IS '수정일시';

CREATE INDEX IX_SPRG_END     ON SUPPORT_PROGRAM (APPLY_END_DE);
CREATE INDEX IX_SPRG_SRC     ON SUPPORT_PROGRAM (SOURCE_CD, APPLY_END_DE);
CREATE INDEX IX_SPRG_RECRUIT ON SUPPORT_PROGRAM (RECRUIT_YN);
CREATE INDEX IX_SPRG_VISIBLE ON SUPPORT_PROGRAM (IS_VISIBLE);


-- SUPPORT_PROGRAM_KSTARTUP_DETAIL: 지원 사업 상세 (K-Startup 전용)
CREATE TABLE SUPPORT_PROGRAM_KSTARTUP_DETAIL (
                                                 PROGRAM_ID          VARCHAR2(50 CHAR)  NOT NULL,
                                                 SOURCE_CD           VARCHAR2(20 CHAR)  NOT NULL,
                                                 APLY_MTHD_VST       VARCHAR2(4000 CHAR),
                                                 APLY_MTHD_PSSR      VARCHAR2(4000 CHAR),
                                                 APLY_MTHD_FAX       VARCHAR2(4000 CHAR),
                                                 APLY_MTHD_EML       VARCHAR2(4000 CHAR),
                                                 APLY_MTHD_ONLI      VARCHAR2(4000 CHAR),
                                                 APLY_MTHD_ETC       VARCHAR2(4000 CHAR),
                                                 APLY_EXCL_TRGT_CTNT CLOB,
                                                 BIZ_ENYY            VARCHAR2(1000 CHAR),
                                                 BIZ_TRGT_AGE        VARCHAR2(1000 CHAR),
                                                 PRFN_MATR           CLOB,
                                                 SPRV_INST           VARCHAR2(200 CHAR),
                                                 PBANC_NTRP_NM       VARCHAR2(1000 CHAR),
                                                 BIZ_GDNC_URL        VARCHAR2(2000 CHAR),
                                                 INTG_PBANC_YN       CHAR(1),
                                                 CREATED_AT          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                                 UPDATED_AT          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                                 CONSTRAINT PK_SPRG_KSTARTUP_DETAIL PRIMARY KEY (SOURCE_CD, PROGRAM_ID),
                                                 CONSTRAINT CK_SPRG_DETAIL_SOURCE CHECK (SOURCE_CD = 'KSTARTUP'),
                                                 CONSTRAINT FK_SPRG_DETAIL FOREIGN KEY (SOURCE_CD, PROGRAM_ID)
                                                     REFERENCES SUPPORT_PROGRAM (SOURCE_CD, PROGRAM_ID)
                                                         ON DELETE CASCADE
);

COMMENT ON TABLE  SUPPORT_PROGRAM_KSTARTUP_DETAIL                      IS '지원 사업 상세 (K-Startup 전용, SUPPORT_PROGRAM과 1:0또는1)';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.APLY_MTHD_VST        IS '방문 접수 설명';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.APLY_MTHD_PSSR       IS '우편 접수 설명';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.APLY_MTHD_FAX        IS '팩스 접수 설명';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.APLY_MTHD_EML        IS '이메일 접수 설명 (원본 자체가 암호화된 문자열로 제공됨)';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.APLY_MTHD_ONLI       IS '온라인 접수 설명';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.APLY_MTHD_ETC        IS '기타 접수 설명';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.APLY_EXCL_TRGT_CTNT  IS '신청 제외 대상 내용';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.BIZ_ENYY             IS '창업 기간';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.BIZ_TRGT_AGE         IS '대상 연령';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.PRFN_MATR            IS '우대 사항';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.SPRV_INST            IS '주관 기관';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.PBANC_NTRP_NM        IS '창업 지원 기관명';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.BIZ_GDNC_URL         IS '사업 안내 URL';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.INTG_PBANC_YN        IS '통합 공고 여부';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.CREATED_AT           IS '생성일시';
COMMENT ON COLUMN SUPPORT_PROGRAM_KSTARTUP_DETAIL.UPDATED_AT           IS '수정일시';

-- 회원/관리자
-- 회원 정보
CREATE TABLE MEMBER (
                        MEMBER_ID       NUMBER(19)         GENERATED ALWAYS AS IDENTITY,
                        LOGIN_ID        VARCHAR2(50 CHAR)  NOT NULL,
                        PASSWORD_HASH   VARCHAR2(255 CHAR) NOT NULL,
                        PASSWORD_SALT   VARCHAR2(255 CHAR),
                        PW_ALGO         VARCHAR2(20 CHAR)  NOT NULL,
                        EMAIL           VARCHAR2(255 CHAR) NOT NULL,
                        NICKNAME        VARCHAR2(50 CHAR)  NOT NULL,
                        ROLE            VARCHAR2(10 CHAR)  DEFAULT 'USER'   NOT NULL,
                        STATUS          VARCHAR2(10 CHAR)  DEFAULT 'ACTIVE' NOT NULL,
                        LAST_LOGIN_AT   TIMESTAMP(6),
                        WITHDRAWN_AT    TIMESTAMP(6),
                        PLAN_UNTIL      TIMESTAMP(6),
                        VERSION         NUMBER(19,0)  DEFAULT 0 NOT NULL,
                        CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                        UPDATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                        CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID),
                        CONSTRAINT UK_MEMBER_LOGIN_ID  UNIQUE (LOGIN_ID),
                        CONSTRAINT UK_MEMBER_EMAIL     UNIQUE (EMAIL),
                        CONSTRAINT CK_MBR_ROLE   CHECK (ROLE   IN ('USER','PREMIUM')),
                        CONSTRAINT CK_MBR_STATUS CHECK (STATUS IN ('ACTIVE','DORMANT','BANNED','WITHDRAWN')),
                        CONSTRAINT CK_MBR_PWALGO CHECK (PW_ALGO IN ('ARGON2ID','BCRYPT')),
                        CONSTRAINT CK_MBR_SALT_SCOPE CHECK (
                            PASSWORD_SALT IS NULL OR PW_ALGO <> 'BCRYPT'
                            ),
                        CONSTRAINT CK_MBR_WITHDRAWN CHECK (STATUS <> 'WITHDRAWN' OR WITHDRAWN_AT IS NOT NULL)
);
COMMENT ON TABLE  MEMBER IS '회원 (로컬 로그인 전용: 아이디/비밀번호, OLTP)';
COMMENT ON COLUMN MEMBER.MEMBER_ID     IS '회원 PK (IDENTITY 대체키)';
COMMENT ON COLUMN MEMBER.LOGIN_ID      IS '로컬 로그인 아이디 (UNIQUE, 필수)';
COMMENT ON COLUMN MEMBER.PASSWORD_HASH IS '비밀번호 해시 (argon2 $argon2.. / bcrypt $2[aby]$, 평문 저장 금지)';
COMMENT ON COLUMN MEMBER.PASSWORD_SALT IS '해시 salt (bcrypt는 salt를 해시에 포함하므로 NULL, 비bcrypt salted 스킴용)';
COMMENT ON COLUMN MEMBER.PW_ALGO       IS '해시 알고리즘 태그(ARGON2ID/BCRYPT)';
COMMENT ON COLUMN MEMBER.EMAIL         IS '이메일 [PII] (UNIQUE, 필수)';
COMMENT ON COLUMN MEMBER.NICKNAME      IS '닉네임 [PII]';
COMMENT ON COLUMN MEMBER.ROLE          IS '권한: USER / PREMIUM';
COMMENT ON COLUMN MEMBER.STATUS        IS '계정 상태: ACTIVE / DORMANT / BANNED / WITHDRAWN';
COMMENT ON COLUMN MEMBER.LAST_LOGIN_AT IS '최근 로그인 시각 (휴면 판정용)';
COMMENT ON COLUMN MEMBER.WITHDRAWN_AT  IS '탈퇴 시각 (STATUS=WITHDRAWN이면 필수; 재활성화 시에도 이력 보존 가능)';
COMMENT ON COLUMN MEMBER.PLAN_UNTIL    IS 'Pro 구독 만료 시각 (NULL 또는 과거면 무료; 결제 확정 시 갱신)';
COMMENT ON COLUMN MEMBER.CREATED_AT    IS '생성 시각';
COMMENT ON COLUMN MEMBER.UPDATED_AT    IS '수정 시각';

CREATE INDEX IX_MEMBER_STATUS ON MEMBER (STATUS);

-- 관리자 계정
CREATE TABLE ADMIN_USER (
                            ADMIN_ID         NUMBER(19)         GENERATED ALWAYS AS IDENTITY,
                            LOGIN_ID         VARCHAR2(50 CHAR)  NOT NULL,
                            PASSWORD_HASH    VARCHAR2(255 CHAR) NOT NULL,
                            PW_ALGO          VARCHAR2(20 CHAR)  DEFAULT 'ARGON2ID' NOT NULL,
                            NAME             VARCHAR2(50 CHAR)  NOT NULL,
                            ROLE             VARCHAR2(15 CHAR)  DEFAULT 'VIEWER' NOT NULL,
                            STATUS           VARCHAR2(10 CHAR)  DEFAULT 'ACTIVE' NOT NULL,
                            FAILED_LOGIN_CNT NUMBER(4)          DEFAULT 0 NOT NULL,
                            LOCKED_AT        TIMESTAMP(6),
                            PW_VERSION       NUMBER(10)         DEFAULT 0 NOT NULL,
                            OTP_ENABLED      CHAR(1 CHAR)       DEFAULT 'N' NOT NULL,
                            OTP_SECRET       VARCHAR2(64 CHAR),
                            OTP_LAST_STEP    NUMBER(19),
                            LAST_LOGIN_AT    TIMESTAMP(6),
                            CREATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                            UPDATED_AT       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                            CONSTRAINT PK_ADMIN_USER PRIMARY KEY (ADMIN_ID),
                            CONSTRAINT UK_ADMIN_USER_LOGIN_ID UNIQUE (LOGIN_ID),
                            CONSTRAINT CK_ADM_ROLE     CHECK (ROLE   IN ('SUPER_ADMIN','OPERATOR','VIEWER')),
                            CONSTRAINT CK_ADM_STATUS   CHECK (STATUS IN ('ACTIVE','LOCKED','DISABLED')),
                            CONSTRAINT CK_ADM_PWALGO   CHECK (PW_ALGO IN ('ARGON2ID','BCRYPT')),
                            CONSTRAINT CK_ADM_FAILCNT  CHECK (FAILED_LOGIN_CNT >= 0),
                            CONSTRAINT CK_ADM_OTP      CHECK (OTP_ENABLED IN ('Y','N'))
);
COMMENT ON TABLE  ADMIN_USER IS '관리자 계정 (백오피스 RBAC)';
COMMENT ON COLUMN ADMIN_USER.ADMIN_ID         IS '관리자 PK (IDENTITY 대체키)';
COMMENT ON COLUMN ADMIN_USER.LOGIN_ID         IS '관리자 로그인 아이디 (UNIQUE)';
COMMENT ON COLUMN ADMIN_USER.PASSWORD_HASH    IS '비밀번호 해시 (Argon2id/bcrypt, 평문 저장 금지)';
COMMENT ON COLUMN ADMIN_USER.PW_ALGO          IS '해시 알고리즘 태그(ARGON2ID/BCRYPT) - 마이그레이션 대비';
COMMENT ON COLUMN ADMIN_USER.NAME             IS '관리자 이름 [PII]';
COMMENT ON COLUMN ADMIN_USER.ROLE             IS '권한: SUPER_ADMIN / OPERATOR / VIEWER';
COMMENT ON COLUMN ADMIN_USER.STATUS           IS '상태: ACTIVE / LOCKED / DISABLED(퇴사 등 비활성)';
COMMENT ON COLUMN ADMIN_USER.FAILED_LOGIN_CNT IS '연속 로그인 실패 횟수 (LOCKED 잠금 트리거용)';
COMMENT ON COLUMN ADMIN_USER.LOCKED_AT        IS '연속 실패 자동 잠금 시각 (쿨다운 자동 해제 판정용; 관리자 수동 잠금은 NULL)';
COMMENT ON COLUMN ADMIN_USER.PW_VERSION       IS '비밀번호 버전(변경 시 +1). 세션 무효화 비교용';
COMMENT ON COLUMN ADMIN_USER.OTP_ENABLED      IS '2단계 인증(TOTP) 사용 여부: Y / N';
COMMENT ON COLUMN ADMIN_USER.OTP_SECRET       IS 'TOTP 비밀키(Base32), 2FA 설정 시 발급 [민감]';
COMMENT ON COLUMN ADMIN_USER.OTP_LAST_STEP    IS '마지막으로 소비한 TOTP 시간 스텝(리플레이 방지). 사용 이력 없으면 NULL';
COMMENT ON COLUMN ADMIN_USER.LAST_LOGIN_AT    IS '최근 로그인 시각';
COMMENT ON COLUMN ADMIN_USER.CREATED_AT       IS '생성 시각';
COMMENT ON COLUMN ADMIN_USER.UPDATED_AT       IS '수정 시각';

-- 관심 상권
CREATE TABLE FAVORITE (
                          FAVORITE_ID     NUMBER(19)        GENERATED ALWAYS AS IDENTITY,
                          MEMBER_ID       NUMBER(19)        NOT NULL,
                          TRDAR_CD        VARCHAR2(20 CHAR) NOT NULL,
                          CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                          UPDATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                          CONSTRAINT PK_FAVORITE PRIMARY KEY (FAVORITE_ID),
                          CONSTRAINT UK_FAVORITE_MEMBER_TRDAR UNIQUE (MEMBER_ID, TRDAR_CD),
                          CONSTRAINT FK_FAVORITE_MEMBER FOREIGN KEY (MEMBER_ID)
                              REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE,
                          CONSTRAINT FK_FAVORITE_TRDAR FOREIGN KEY (TRDAR_CD)
                              REFERENCES TRDAR (TRDAR_CD)
);
COMMENT ON TABLE  FAVORITE IS '회원이 찜한 상권 (회원당 상권 중복 불가; 회원 하드삭제 시 CASCADE = 일시적 선호 데이터)';
COMMENT ON COLUMN FAVORITE.FAVORITE_ID IS '찜 PK (IDENTITY 대체키)';
COMMENT ON COLUMN FAVORITE.MEMBER_ID   IS '회원 FK (MEMBER 탈퇴 시 CASCADE 삭제)';
COMMENT ON COLUMN FAVORITE.TRDAR_CD    IS '상권 코드 FK -> TRDAR';
COMMENT ON COLUMN FAVORITE.CREATED_AT  IS '찜한 시각';
COMMENT ON COLUMN FAVORITE.UPDATED_AT  IS '수정 시각';

CREATE INDEX IX_FAVORITE_TRDAR ON FAVORITE (TRDAR_CD);

-- AI 리포트 생성 이력
CREATE TABLE LLM_REPORT (
                            REPORT_ID       NUMBER(19)         GENERATED ALWAYS AS IDENTITY,
                            MEMBER_ID       NUMBER(19),
                            TRDAR_CD        VARCHAR2(20 CHAR)  NOT NULL,
                            STDR_YYQU_CD    CHAR(5 CHAR),
                            INDUTY_CD       VARCHAR2(20 CHAR),
    PROMPT          CLOB               NOT NULL,
    RESULT_TEXT     CLOB               NOT NULL,
    MODEL_NAME      VARCHAR2(100 CHAR) NOT NULL,
    TOKEN_CNT       NUMBER(10,0),
    CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_LLM_REPORT PRIMARY KEY (REPORT_ID),
    CONSTRAINT FK_LLM_REPORT_MEMBER FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBER (MEMBER_ID) ON DELETE SET NULL,
    CONSTRAINT FK_LLM_REPORT_TRDAR FOREIGN KEY (TRDAR_CD)
        REFERENCES TRDAR (TRDAR_CD),
    CONSTRAINT FK_LLM_REPORT_QUARTER FOREIGN KEY (STDR_YYQU_CD)
        REFERENCES DIM_QUARTER (STDR_YYQU_CD),
    CONSTRAINT FK_LLM_REPORT_INDUTY FOREIGN KEY (INDUTY_CD)
        REFERENCES INDUTY (INDUTY_CD),
    CONSTRAINT CK_LLM_TOKEN_CNT CHECK (TOKEN_CNT IS NULL OR TOKEN_CNT >= 0)
);
COMMENT ON TABLE  LLM_REPORT IS 'AI(Gemini) 리포트 생성 이력';
COMMENT ON COLUMN LLM_REPORT.REPORT_ID    IS '리포트 PK (IDENTITY 대체키)';
COMMENT ON COLUMN LLM_REPORT.MEMBER_ID    IS '회원 FK (게스트 생성 허용 -> NULL; 회원 하드삭제 시 SET NULL = 이력/분석 보존)';
COMMENT ON COLUMN LLM_REPORT.TRDAR_CD     IS '대상 상권 코드 FK -> TRDAR';
COMMENT ON COLUMN LLM_REPORT.STDR_YYQU_CD IS '기준 분기 코드 FK -> DIM_QUARTER (분기 무관 리포트는 NULL)';
COMMENT ON COLUMN LLM_REPORT.INDUTY_CD    IS '대상 업종 코드 FK -> INDUTY (상권 전체 리포트는 NULL)';
COMMENT ON COLUMN LLM_REPORT.PROMPT       IS 'LLM 입력 프롬프트';
COMMENT ON COLUMN LLM_REPORT.RESULT_TEXT  IS 'LLM 생성 결과 텍스트';
COMMENT ON COLUMN LLM_REPORT.MODEL_NAME   IS '사용 모델명 (예: gemini-2.5-pro)';
COMMENT ON COLUMN LLM_REPORT.TOKEN_CNT    IS '소모 토큰 수 (비용 집계, >=0)';
COMMENT ON COLUMN LLM_REPORT.CREATED_AT   IS '생성 시각';
COMMENT ON COLUMN LLM_REPORT.UPDATED_AT   IS '수정 시각';

CREATE INDEX IX_LLM_REPORT_MEMBER  ON LLM_REPORT (MEMBER_ID);
CREATE INDEX IX_LLM_REPORT_TRDAR   ON LLM_REPORT (TRDAR_CD);
CREATE INDEX IX_LLM_REPORT_QUARTER ON LLM_REPORT (STDR_YYQU_CD);

-- 검색 로그
CREATE TABLE SEARCH_LOG (
                            SEARCH_ID       NUMBER(19)         GENERATED ALWAYS AS IDENTITY,
                            MEMBER_ID       NUMBER(19),
                            KEYWORD         VARCHAR2(200 CHAR) NOT NULL,
                            TRDAR_CD        VARCHAR2(20 CHAR),
                            SEARCHED_AT     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                            CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                            UPDATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                            CONSTRAINT PK_SEARCH_LOG PRIMARY KEY (SEARCH_ID),
                            CONSTRAINT FK_SEARCH_LOG_MEMBER FOREIGN KEY (MEMBER_ID)
                                REFERENCES MEMBER (MEMBER_ID) ON DELETE SET NULL,
                            CONSTRAINT FK_SEARCH_LOG_TRDAR FOREIGN KEY (TRDAR_CD)
                                REFERENCES TRDAR (TRDAR_CD)
);
COMMENT ON TABLE  SEARCH_LOG IS '검색 로그 (등록 전용, 최소 컬럼)';
COMMENT ON COLUMN SEARCH_LOG.SEARCH_ID   IS '검색 로그 PK (IDENTITY 대체키)';
COMMENT ON COLUMN SEARCH_LOG.MEMBER_ID   IS '회원 FK (비로그인 검색 -> NULL, 탈퇴 시 SET NULL)';
COMMENT ON COLUMN SEARCH_LOG.KEYWORD     IS '검색 키워드';
COMMENT ON COLUMN SEARCH_LOG.TRDAR_CD    IS '검색 결과로 매칭된 상권 코드 FK -> TRDAR (없으면 NULL)';
COMMENT ON COLUMN SEARCH_LOG.SEARCHED_AT IS '검색 시각';
COMMENT ON COLUMN SEARCH_LOG.CREATED_AT  IS '생성 시각';
COMMENT ON COLUMN SEARCH_LOG.UPDATED_AT  IS '수정 시각';

CREATE INDEX IX_SEARCH_LOG_MEMBER   ON SEARCH_LOG (MEMBER_ID);
CREATE INDEX IX_SEARCH_LOG_TRDAR    ON SEARCH_LOG (TRDAR_CD);
CREATE INDEX IX_SEARCH_LOG_SEARCHED ON SEARCH_LOG (SEARCHED_AT);

-- 관리자 작업 로그
CREATE TABLE ADMIN_AUDIT_LOG (
                                 AUDIT_ID        NUMBER(19)         GENERATED ALWAYS AS IDENTITY,
                                 ADMIN_ID        NUMBER(19)         NOT NULL,
                                 ACTION          VARCHAR2(50 CHAR)  NOT NULL,
                                 TARGET_TYPE     VARCHAR2(50 CHAR),
                                 TARGET_ID       VARCHAR2(100 CHAR),
                                 DETAIL          CLOB,
                                 IP_ADDR         VARCHAR2(45 CHAR),
                                 CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                 UPDATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                                 CONSTRAINT PK_ADMIN_AUDIT_LOG PRIMARY KEY (AUDIT_ID),
                                 CONSTRAINT FK_ADMIN_AUDIT_LOG_ADMIN FOREIGN KEY (ADMIN_ID)
                                     REFERENCES ADMIN_USER (ADMIN_ID)
);
COMMENT ON TABLE  ADMIN_AUDIT_LOG IS '관리자 감사 로그 (관리자 행위 기록)';
COMMENT ON COLUMN ADMIN_AUDIT_LOG.AUDIT_ID    IS '감사 로그 PK';
COMMENT ON COLUMN ADMIN_AUDIT_LOG.ADMIN_ID    IS '수행 관리자 FK -> ADMIN_USER';
COMMENT ON COLUMN ADMIN_AUDIT_LOG.ACTION      IS '행위 코드 (예: MEMBER_BAN / NOTICE_CREATE / BATCH_RERUN)';
COMMENT ON COLUMN ADMIN_AUDIT_LOG.TARGET_TYPE IS '대상 유형 (예: MEMBER / NOTICE / BATCH_JOB)';
COMMENT ON COLUMN ADMIN_AUDIT_LOG.TARGET_ID   IS '대상 식별자 (문자열, 다형 참조)';
COMMENT ON COLUMN ADMIN_AUDIT_LOG.DETAIL      IS '상세 변경 내역';
COMMENT ON COLUMN ADMIN_AUDIT_LOG.IP_ADDR     IS '요청 IP [PII] (IPv4/IPv6, 최대 45자)';
COMMENT ON COLUMN ADMIN_AUDIT_LOG.CREATED_AT  IS '기록 시각';
COMMENT ON COLUMN ADMIN_AUDIT_LOG.UPDATED_AT  IS '수정 시각';

CREATE INDEX IX_ADMIN_AUDIT_LOG_ADMIN   ON ADMIN_AUDIT_LOG (ADMIN_ID);
CREATE INDEX IX_ADMIN_AUDIT_LOG_TARGET  ON ADMIN_AUDIT_LOG (TARGET_TYPE, TARGET_ID);

-- 배치 실행 로그
CREATE TABLE BATCH_JOB_LOG (
                               JOB_LOG_ID      NUMBER(19)         GENERATED ALWAYS AS IDENTITY,
                               JOB_NAME        VARCHAR2(100 CHAR) NOT NULL,
                               DATASET_CD      VARCHAR2(30 CHAR)  NOT NULL,
                               STDR_YYQU_CD    CHAR(5 CHAR),
    STATUS          VARCHAR2(10 CHAR)  NOT NULL,
    STARTED_AT      TIMESTAMP(6)       NOT NULL,
    ENDED_AT        TIMESTAMP(6),
    PROCESSED_CNT   NUMBER(12,0) DEFAULT 0 NOT NULL,
    FAILED_CNT      NUMBER(12,0) DEFAULT 0 NOT NULL,
    ERROR_MSG       CLOB,
    TRIGGERED_BY    VARCHAR2(50 CHAR)  NOT NULL,
    CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_BATCH_JOB_LOG PRIMARY KEY (JOB_LOG_ID),
    CONSTRAINT FK_BATCH_JOB_LOG_QUARTER FOREIGN KEY (STDR_YYQU_CD)
        REFERENCES DIM_QUARTER (STDR_YYQU_CD),
    CONSTRAINT CK_BJL_DATASET CHECK (DATASET_CD IN
        ('INDUSTRY_NEWS','INDUSTRY_TRADEMARK','SUPPORT_PROGRAM','TRDAR','SALES','STORE_STAT','TRDAR_CHANGE',
         'STREET_POP','RESIDENT_POP','ATTRACTION','APT','RENT','FRANCHISE','FRANCHISE_STAT',
         'WORKER_POP','FACILITY','INCOME_CONSUM','APARTMENT')),
    CONSTRAINT CK_BJL_STATUS       CHECK (STATUS IN ('RUNNING','SUCCESS','FAILED','PARTIAL')),
    CONSTRAINT CK_BJL_PROCESSED_CNT CHECK (PROCESSED_CNT >= 0),
    CONSTRAINT CK_BJL_FAILED_CNT    CHECK (FAILED_CNT >= 0),
    CONSTRAINT CK_BJL_TIME_ORDER CHECK (ENDED_AT IS NULL OR ENDED_AT >= STARTED_AT),
    CONSTRAINT CK_BJL_RUNNING_END CHECK (
        (STATUS = 'RUNNING' AND ENDED_AT IS NULL)
        OR (STATUS <> 'RUNNING' AND ENDED_AT IS NOT NULL)
    )
);
COMMENT ON TABLE  BATCH_JOB_LOG IS '배치 적재 이력, 관리자 "데이터 적재 현황" 대시보드 소스';
COMMENT ON COLUMN BATCH_JOB_LOG.JOB_LOG_ID    IS '적재 이력 PK (IDENTITY 대체키)';
COMMENT ON COLUMN BATCH_JOB_LOG.JOB_NAME      IS '배치 잡 이름';
COMMENT ON COLUMN BATCH_JOB_LOG.DATASET_CD    IS '적재 대상 공공데이터셋 코드 (예: SALES / STORE_STAT / STREET_POP)';
COMMENT ON COLUMN BATCH_JOB_LOG.STDR_YYQU_CD  IS '적재 대상 분기 코드 FK -> DIM_QUARTER (분기 무관 잡은 NULL)';
COMMENT ON COLUMN BATCH_JOB_LOG.STATUS        IS '상태: RUNNING / SUCCESS / FAILED / PARTIAL';
COMMENT ON COLUMN BATCH_JOB_LOG.STARTED_AT    IS '시작 시각';
COMMENT ON COLUMN BATCH_JOB_LOG.ENDED_AT      IS '종료 시각 (RUNNING이면 NULL)';
COMMENT ON COLUMN BATCH_JOB_LOG.PROCESSED_CNT IS '처리 성공 건수 (>=0)';
COMMENT ON COLUMN BATCH_JOB_LOG.FAILED_CNT    IS '처리 실패 건수 (>=0)';
COMMENT ON COLUMN BATCH_JOB_LOG.ERROR_MSG     IS '오류 메시지 (실패/부분 성공 시)';
COMMENT ON COLUMN BATCH_JOB_LOG.TRIGGERED_BY  IS '트리거 주체 (예: SCHEDULER / 관리자 login_id)';
COMMENT ON COLUMN BATCH_JOB_LOG.CREATED_AT    IS '생성 시각';
COMMENT ON COLUMN BATCH_JOB_LOG.UPDATED_AT    IS '수정 시각 (RUNNING->SUCCESS 등 상태 전이 시 갱신)';

CREATE INDEX IX_BATCH_JOB_LOG_DASH
    ON BATCH_JOB_LOG (DATASET_CD, STDR_YYQU_CD, STARTED_AT DESC, STATUS);
CREATE INDEX IX_BATCH_JOB_LOG_QUARTER ON BATCH_JOB_LOG (STDR_YYQU_CD);
CREATE INDEX IX_BATCH_JOB_LOG_STATUS  ON BATCH_JOB_LOG (STATUS, STARTED_AT DESC);

-- 외부 API 호출량
CREATE TABLE API_USAGE_LOG (
                               USAGE_ID        NUMBER(19)        GENERATED ALWAYS AS IDENTITY,
                               API_NAME        VARCHAR2(20 CHAR) NOT NULL,
                               USAGE_DATE      DATE              NOT NULL,
                               CALL_CNT        NUMBER(12,0) DEFAULT 0 NOT NULL,
                               DAILY_LIMIT     NUMBER(12,0)      NOT NULL,
                               CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                               UPDATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                               CONSTRAINT PK_API_USAGE_LOG PRIMARY KEY (USAGE_ID),
                               CONSTRAINT UK_API_USAGE_LOG_NAME_DATE UNIQUE (API_NAME, USAGE_DATE),
                               CONSTRAINT CK_API_NAME CHECK (API_NAME IN
                                                             ('SBIZ','NTS','FTC_FRANCHISE','REB_RONE','SEOUL','KAKAO','GEMINI','GEMINI_NEWS','KIPRIS')),
                               CONSTRAINT CK_API_CALL_CNT    CHECK (CALL_CNT >= 0),
                               CONSTRAINT CK_API_DAILY_LIMIT CHECK (DAILY_LIMIT > 0),
                               CONSTRAINT CK_API_USAGE_DATE_TRUNC CHECK (USAGE_DATE = TRUNC(USAGE_DATE))
);
COMMENT ON TABLE  API_USAGE_LOG IS '외부 API 일자별 호출량 집계, 일 한도 알림(예: SBIZ 10,000/일) 모니터링';
COMMENT ON COLUMN API_USAGE_LOG.USAGE_ID    IS '집계 행 PK (IDENTITY 대체키)';
COMMENT ON COLUMN API_USAGE_LOG.API_NAME    IS 'API 코드: SBIZ / NTS / FTC_FRANCHISE / REB_RONE / SEOUL / KAKAO / GEMINI(AI 리포트) / GEMINI_NEWS(뉴스 요약) / KIPRIS(상표검색)';
COMMENT ON COLUMN API_USAGE_LOG.USAGE_DATE  IS '사용 일자 (시간 성분 없음, API당 하루 1행; 조회는 USAGE_DATE = TRUNC(SYSDATE))';
COMMENT ON COLUMN API_USAGE_LOG.CALL_CNT    IS '당일 누적 호출 수 (MERGE로 증분)';
COMMENT ON COLUMN API_USAGE_LOG.DAILY_LIMIT IS '당일 호출 한도 (>0, 예: SBIZ=10000)';
COMMENT ON COLUMN API_USAGE_LOG.CREATED_AT  IS '집계 행 생성 시각';
COMMENT ON COLUMN API_USAGE_LOG.UPDATED_AT  IS '집계 행 갱신 시각 (증분 시 갱신)';

-- 공지사항
CREATE TABLE NOTICE (
                        NOTICE_ID       NUMBER(19)         GENERATED ALWAYS AS IDENTITY,
                        TITLE           VARCHAR2(200 CHAR) NOT NULL,
                        CONTENT         CLOB               NOT NULL,
                        ADMIN_ID        NUMBER(19)         NOT NULL,
                        IS_PINNED       CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    VIEW_CNT        NUMBER(12,0) DEFAULT 0   NOT NULL,
    STATUS          VARCHAR2(10 CHAR) DEFAULT 'DRAFT' NOT NULL,
    CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NOTICE PRIMARY KEY (NOTICE_ID),
    CONSTRAINT FK_NOTICE_ADMIN FOREIGN KEY (ADMIN_ID)
        REFERENCES ADMIN_USER (ADMIN_ID),
    CONSTRAINT CK_NTC_IS_PINNED CHECK (IS_PINNED IN ('Y','N')),
    CONSTRAINT CK_NTC_VIEW_CNT  CHECK (VIEW_CNT >= 0),
    CONSTRAINT CK_NTC_STATUS    CHECK (STATUS IN ('DRAFT','PUBLISHED','HIDDEN'))
);
COMMENT ON TABLE  NOTICE IS '공지사항';
COMMENT ON COLUMN NOTICE.NOTICE_ID  IS '공지 PK (IDENTITY 대체키)';
COMMENT ON COLUMN NOTICE.TITLE      IS '제목';
COMMENT ON COLUMN NOTICE.CONTENT    IS '본문';
COMMENT ON COLUMN NOTICE.ADMIN_ID   IS '작성 관리자 FK -> ADMIN_USER';
COMMENT ON COLUMN NOTICE.IS_PINNED  IS '상단 고정 여부: Y / N';
COMMENT ON COLUMN NOTICE.VIEW_CNT   IS '조회 수 (>=0)';
COMMENT ON COLUMN NOTICE.STATUS     IS '상태: DRAFT / PUBLISHED / HIDDEN';
COMMENT ON COLUMN NOTICE.CREATED_AT IS '생성 시각';
COMMENT ON COLUMN NOTICE.UPDATED_AT IS '수정 시각';

CREATE INDEX IX_NOTICE_ADMIN ON NOTICE (ADMIN_ID);
CREATE INDEX IX_NOTICE_LIST ON NOTICE (STATUS, IS_PINNED, CREATED_AT DESC);

-- 1:1 문의
CREATE TABLE INQUIRY (
                         INQUIRY_ID      NUMBER(19)         GENERATED ALWAYS AS IDENTITY,
                         MEMBER_ID       NUMBER(19),
                         TITLE           VARCHAR2(200 CHAR) NOT NULL,
                         CONTENT         CLOB               NOT NULL,
                         STATUS          VARCHAR2(10 CHAR) DEFAULT 'OPEN' NOT NULL,
                         ANSWER          CLOB,
                         ANSWERED_BY     NUMBER(19),
                         ANSWERED_AT     TIMESTAMP(6),
                         ANSWER_READ_AT  TIMESTAMP(6),
                         VERSION         NUMBER(19)   DEFAULT 0 NOT NULL,
                         CREATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                         UPDATED_AT      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                         CONSTRAINT PK_INQUIRY PRIMARY KEY (INQUIRY_ID),
                         CONSTRAINT FK_INQUIRY_MEMBER FOREIGN KEY (MEMBER_ID)
                             REFERENCES MEMBER (MEMBER_ID) ON DELETE SET NULL,
                         CONSTRAINT FK_INQUIRY_ADMIN FOREIGN KEY (ANSWERED_BY)
                             REFERENCES ADMIN_USER (ADMIN_ID),
                         CONSTRAINT CK_INQ_STATUS CHECK (STATUS IN ('OPEN','ANSWERED','CLOSED')),
                         CONSTRAINT CK_INQ_ANSWERED CHECK (
                             STATUS <> 'ANSWERED'
                                 OR (ANSWER IS NOT NULL AND ANSWERED_BY IS NOT NULL AND ANSWERED_AT IS NOT NULL)
                             )
);
COMMENT ON TABLE  INQUIRY IS '1:1 문의';
COMMENT ON COLUMN INQUIRY.INQUIRY_ID  IS '문의 PK (IDENTITY 대체키)';
COMMENT ON COLUMN INQUIRY.MEMBER_ID   IS '문의 회원 FK (게스트 문의 -> NULL; 회원 하드삭제 시 SET NULL = 문의 이력 보존)';
COMMENT ON COLUMN INQUIRY.TITLE       IS '제목';
COMMENT ON COLUMN INQUIRY.CONTENT     IS '문의 본문';
COMMENT ON COLUMN INQUIRY.STATUS      IS '상태: OPEN / ANSWERED / CLOSED';
COMMENT ON COLUMN INQUIRY.ANSWER      IS '답변 본문';
COMMENT ON COLUMN INQUIRY.ANSWERED_BY IS '답변 관리자 FK -> ADMIN_USER (nullable)';
COMMENT ON COLUMN INQUIRY.ANSWERED_AT IS '답변 시각 (ANSWERED 상태에서 필수)';
COMMENT ON COLUMN INQUIRY.ANSWER_READ_AT IS '회원이 답변을 처음 열람한 시각 (NULL이면 미확인 = 새 답변 알림)';
COMMENT ON COLUMN INQUIRY.VERSION     IS '낙관적 락 버전 (동시 답변 경합 방지)';
COMMENT ON COLUMN INQUIRY.CREATED_AT  IS '생성 시각';
COMMENT ON COLUMN INQUIRY.UPDATED_AT  IS '수정 시각';

CREATE INDEX IX_INQUIRY_MEMBER ON INQUIRY (MEMBER_ID);
CREATE INDEX IX_INQUIRY_ADMIN  ON INQUIRY (ANSWERED_BY);
CREATE INDEX IX_INQUIRY_STATUS ON INQUIRY (STATUS, CREATED_AT);

-- 뉴스 동향 llm 인사이트 저장

CREATE TABLE INDUSTRY_NEWS_INSIGHT (
                                       INDUTY_CD      VARCHAR2(20)  NOT NULL,
                                       INDUTY_NM      VARCHAR2(50)  NOT NULL,
                                       YEAR_MONTH     VARCHAR2(7)   NOT NULL,
                                       INSIGHT_TEXT   CLOB          NOT NULL,
                                       BASED_ON_COUNT NUMBER,
                                       CREATED_AT     TIMESTAMP(6)  NOT NULL,
                                       CONSTRAINT PK_NEWS_INSIGHT PRIMARY KEY (INDUTY_CD, YEAR_MONTH)
);

COMMENT ON TABLE  INDUSTRY_NEWS_INSIGHT               IS '업종별 월간 뉴스 AI 인사이트 (원문 미저장, 요약만 보관)';
COMMENT ON COLUMN INDUSTRY_NEWS_INSIGHT.INDUTY_CD      IS '업종 코드';
COMMENT ON COLUMN INDUSTRY_NEWS_INSIGHT.INDUTY_NM      IS '업종명(한글)';
COMMENT ON COLUMN INDUSTRY_NEWS_INSIGHT.YEAR_MONTH     IS '인사이트 대상 연월 (예: 2026-07)';
COMMENT ON COLUMN INDUSTRY_NEWS_INSIGHT.INSIGHT_TEXT   IS 'LLM이 생성한 업종 동향 요약 (원문 뉴스 아님)';
COMMENT ON COLUMN INDUSTRY_NEWS_INSIGHT.BASED_ON_COUNT IS '요약 생성에 근거로 쓴 필터 통과 기사 건수(참고용)';
COMMENT ON COLUMN INDUSTRY_NEWS_INSIGHT.CREATED_AT     IS '생성 시각';


-- 결제 주문 (요금제 결제, 토스페이먼츠 승인 결과 반영)
CREATE TABLE PAYMENT_ORDER (
                               ORDER_ID      VARCHAR2(64 CHAR)  NOT NULL,
                               MEMBER_ID     NUMBER(19),
                               PLAN_CD       VARCHAR2(20 CHAR)  NOT NULL,
                               BILLING_CYCLE VARCHAR2(10 CHAR)  NOT NULL,
                               AMOUNT        NUMBER(12,0)       NOT NULL,
                               STATUS        VARCHAR2(10 CHAR) DEFAULT 'PENDING' NOT NULL,
                               ORDER_NAME    VARCHAR2(100 CHAR) NOT NULL,
                               PAYMENT_KEY   VARCHAR2(200 CHAR),
                               APPROVED_AT   TIMESTAMP(6),
                               VERSION       NUMBER(19)   DEFAULT 0 NOT NULL,
                               CREATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                               UPDATED_AT    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
                               CONSTRAINT PK_PAYMENT_ORDER PRIMARY KEY (ORDER_ID),
                               CONSTRAINT FK_PAYMENT_ORDER_MEMBER FOREIGN KEY (MEMBER_ID)
                                   REFERENCES MEMBER (MEMBER_ID) ON DELETE SET NULL,
                               CONSTRAINT CK_PAY_STATUS CHECK (STATUS IN ('PENDING','PAID','FAILED','CANCELED')),
                               CONSTRAINT CK_PAY_CYCLE  CHECK (BILLING_CYCLE IN ('MONTHLY','YEARLY')),
                               CONSTRAINT CK_PAY_AMOUNT CHECK (AMOUNT > 0)
);
CREATE INDEX IX_PAYMENT_ORDER_MEMBER ON PAYMENT_ORDER (MEMBER_ID);
COMMENT ON TABLE  PAYMENT_ORDER IS '요금제 결제 주문. 서버가 금액을 확정해 저장하고 승인 전에 대조한다(위변조 방지)';
COMMENT ON COLUMN PAYMENT_ORDER.ORDER_ID      IS '주문 ID (UUID, 토스 orderId로 사용)';
COMMENT ON COLUMN PAYMENT_ORDER.MEMBER_ID     IS '결제 회원 (하드삭제 시 NULL, 결제 기록은 보존)';
COMMENT ON COLUMN PAYMENT_ORDER.PLAN_CD       IS '플랜 코드 (현재 PRO)';
COMMENT ON COLUMN PAYMENT_ORDER.BILLING_CYCLE IS '결제 주기: MONTHLY / YEARLY';
COMMENT ON COLUMN PAYMENT_ORDER.AMOUNT        IS '서버가 확정한 결제 금액(원)';
COMMENT ON COLUMN PAYMENT_ORDER.STATUS        IS 'PENDING(결제창 진입) / PAID(승인) / FAILED(승인 실패) / CANCELED(환불)';
COMMENT ON COLUMN PAYMENT_ORDER.PAYMENT_KEY   IS '토스 paymentKey (승인 후 기록)';
COMMENT ON COLUMN PAYMENT_ORDER.APPROVED_AT   IS '토스 승인 시각';
COMMENT ON COLUMN PAYMENT_ORDER.VERSION       IS '낙관적 락 버전 (동시 승인 경합 방지)';


-- Spring Session JDBC 세션 저장소(재배포/재시작에도 로그인 유지, 다중 인스턴스 대응).
-- Spring Session 공식 Oracle 스키마와 동일. 만료 세션은 Spring Session이 주기적으로 정리한다.
CREATE TABLE SPRING_SESSION (
    PRIMARY_ID            CHAR(36 CHAR)     NOT NULL,
    SESSION_ID            CHAR(36 CHAR)     NOT NULL,
    CREATION_TIME         NUMBER(19,0)      NOT NULL,
    LAST_ACCESS_TIME      NUMBER(19,0)      NOT NULL,
    MAX_INACTIVE_INTERVAL NUMBER(10,0)      NOT NULL,
    EXPIRY_TIME           NUMBER(19,0)      NOT NULL,
    PRINCIPAL_NAME        VARCHAR2(100 CHAR),
    CONSTRAINT SPRING_SESSION_PK PRIMARY KEY (PRIMARY_ID)
);
CREATE UNIQUE INDEX SPRING_SESSION_IX1 ON SPRING_SESSION (SESSION_ID);
CREATE INDEX SPRING_SESSION_IX2 ON SPRING_SESSION (EXPIRY_TIME);
CREATE INDEX SPRING_SESSION_IX3 ON SPRING_SESSION (PRINCIPAL_NAME);

CREATE TABLE SPRING_SESSION_ATTRIBUTES (
    SESSION_PRIMARY_ID CHAR(36 CHAR)      NOT NULL,
    ATTRIBUTE_NAME     VARCHAR2(200 CHAR) NOT NULL,
    ATTRIBUTE_BYTES    BLOB               NOT NULL,
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
    CONSTRAINT SPRING_SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID)
        REFERENCES SPRING_SESSION (PRIMARY_ID) ON DELETE CASCADE
);
