-- 운영 대시보드 데모용 샘플 데이터 (BATCH_JOB_LOG, API_USAGE_LOG)
-- 감사 로그(ADMIN_AUDIT_LOG)는 관리자 행위로 실제 기록되므로 시드하지 않는다.
-- 배치는 스케줄러가 아직 없어 이력이 비어 화면 확인용 샘플을 넣는다. 재실행 안전(idempotent).

-- 배치 적재 이력 (이력이 없을 때만)
INSERT INTO BATCH_JOB_LOG (JOB_NAME, DATASET_CD, STATUS, STARTED_AT, ENDED_AT, PROCESSED_CNT, FAILED_CNT, ERROR_MSG, TRIGGERED_BY)
SELECT * FROM (
  SELECT '추정매출 적재',   'SALES',      'SUCCESS', TRUNC(SYSDATE)+4/24+12/1440, TRUNC(SYSDATE)+4/24+15/1440, 1247000, 0,   NULL,               'SCHEDULER' FROM DUAL UNION ALL
  SELECT '점포 적재',       'STORE_STAT', 'SUCCESS', TRUNC(SYSDATE)+4/24+16/1440, TRUNC(SYSDATE)+4/24+20/1440, 340120,  0,   NULL,               'SCHEDULER' FROM DUAL UNION ALL
  SELECT '유동인구 적재',   'STREET_POP', 'PARTIAL', TRUNC(SYSDATE)+4/24+21/1440, TRUNC(SYSDATE)+4/24+26/1440, 892400,  120, 'API 응답 일부 지연', 'SCHEDULER' FROM DUAL UNION ALL
  SELECT '상가 임대료 적재', 'RENT',      'SUCCESS', TRUNC(SYSDATE)+4/24+27/1440, TRUNC(SYSDATE)+4/24+29/1440, 51200,   0,   NULL,               'SCHEDULER' FROM DUAL UNION ALL
  SELECT '프랜차이즈 적재', 'FRANCHISE',  'FAILED',  TRUNC(SYSDATE)+4/24+30/1440, TRUNC(SYSDATE)+4/24+31/1440, 0,       0,   'FTC API 인증 실패',  'SCHEDULER' FROM DUAL
) src
WHERE NOT EXISTS (SELECT 1 FROM BATCH_JOB_LOG);

-- 오늘 API 사용량 (오늘 것만 초기화 후 재삽입)
DELETE FROM API_USAGE_LOG WHERE USAGE_DATE = TRUNC(SYSDATE);
INSERT INTO API_USAGE_LOG (API_NAME, USAGE_DATE, CALL_CNT, DAILY_LIMIT)
  SELECT 'SBIZ',          TRUNC(SYSDATE), 3200, 10000 FROM DUAL UNION ALL
  SELECT 'NTS',           TRUNC(SYSDATE), 1450, 5000  FROM DUAL UNION ALL
  SELECT 'FTC_FRANCHISE', TRUNC(SYSDATE), 780,  1000  FROM DUAL UNION ALL
  SELECT 'REB_RONE',      TRUNC(SYSDATE), 210,  500   FROM DUAL UNION ALL
  SELECT 'SEOUL',         TRUNC(SYSDATE), 9100, 10000 FROM DUAL UNION ALL
  SELECT 'KAKAO',         TRUNC(SYSDATE), 4200, 30000 FROM DUAL;
COMMIT;
