package com.sangkwon.sangkwonplatform.admin.ops;

public enum AuditAction {
    LOGIN,
    LOGIN_FAILED,
    LOGOUT,
    ACCOUNT_LOCKED,
    ADMIN_CREATE,
    ADMIN_ROLE_UPDATE,
    ADMIN_STATUS_UPDATE,
    MEMBER_STATUS_UPDATE,
    SUPPORT_VISIBILITY_UPDATE,
    NOTICE_CREATE,
    NOTICE_UPDATE,
    NOTICE_DELETE,
    INQUIRY_ANSWER,
    INQUIRY_CLOSE,
    PASSWORD_RESET,
    PASSWORD_CHANGE,
    NAME_UPDATE,
    OTP_SETUP,
    OTP_ENABLE,
    OTP_DISABLE
}
